//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericAirways.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class PassengerRecord
    {
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[StringLength(30, ErrorMessage = "FirstName has a maximum length of 30.")]
    	[Required(ErrorMessage = "FirstName is required.")]
    	[DataMember(Name = "FirstName", IsRequired = true)]
    	public string FirstName { get; set; }
        
    	[StringLength(30, ErrorMessage = "LastName has a maximum length of 30.")]
    	[Required(ErrorMessage = "LastName is required.")]
    	[DataMember(Name = "LastName", IsRequired = true)]
    	public string LastName { get; set; }
        
    	[Required(ErrorMessage = "RecordLocatorId is required.")]
    	[DataMember(Name = "RecordLocatorId", IsRequired = true)]
    	public int RecordLocatorId { get; set; }
        
    	[StringLength(50, ErrorMessage = "LineData has a maximum length of 50.")]
    	[DataMember(Name = "LineData")]
    	public string LineData { get; set; }
    
        [DataMember(Name = "RecordLocator")]
    	public virtual RecordLocator RecordLocator { get; set; }
    }
}
