//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericAirways.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class RecordLocator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordLocator()
        {
            this.PassengerRecord = new HashSet<PassengerRecord>();
        }
    
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[Required(ErrorMessage = "PNLFileId is required.")]
    	[DataMember(Name = "PNLFileId", IsRequired = true)]
    	public int PNLFileId { get; set; }
        
    	[StringLength(6, ErrorMessage = "Code has a maximum length of 6.")]
    	[Required(ErrorMessage = "Code is required.")]
    	[DataMember(Name = "Code", IsRequired = true)]
    	public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember(Name = "PassengerRecord")]
    	public virtual ICollection<PassengerRecord> PassengerRecord { get; set; }
        [DataMember(Name = "PNLFile")]
    	public virtual PNLFile PNLFile { get; set; }
    }
}
