//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericAirways.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class User
    {
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[StringLength(30, ErrorMessage = "FirstName has a maximum length of 30.")]
    	[Required(ErrorMessage = "FirstName is required.")]
    	[DataMember(Name = "FirstName", IsRequired = true)]
    	public string FirstName { get; set; }
        
    	[StringLength(30, ErrorMessage = "LastName has a maximum length of 30.")]
    	[Required(ErrorMessage = "LastName is required.")]
    	[DataMember(Name = "LastName", IsRequired = true)]
    	public string LastName { get; set; }

    	[StringLength(50, ErrorMessage = "UserName has a maximum length of 50.")]
		[Required(ErrorMessage = "UserName is required.")]
    	[DataMember(Name = "UserName")]
    	public string UserName { get; set; }

    	[StringLength(50, ErrorMessage = "LineData has a maximum length of 50.")]
		[Required(ErrorMessage = "Password is required.")]
    	[DataMember(Name = "Password")]
    	public string Password { get; set; }

		[StringLength(50, ErrorMessage = "Email has a maximum length of 50.")]
		[Required(ErrorMessage = "Email is required.")]
    	[DataMember(Name = "Email")]
    	public string Email { get; set; }

		//[StringLength(50, ErrorMessage = "Email has a maximum length of 50.")]
		//[Required(ErrorMessage = "Email is required.")]
    	//[DataMember(Name = "Email")]
    	public long? FacebookId { get; set; }
    
    }
}
